export const AUDIT_EVENT_SUMD_CREATEANKETA = 'SUMD_CREATEANKETA';
export const AUDIT_EVENT_SUMD_SAVEANKETA = 'SUMD_SAVEANKETA';
export const AUDIT_EVENT_SUMD_DELETEANKETA = 'SUMD_DELETEANKETA';
export const AUDIT_EVENT_SUMD_HOLDANKETA = 'SUMD_HOLDANKETA';
export const AUDIT_EVENT_SUMD_BLOCKAPPROVE = 'SUMD_BLOCKAPPROVE';
export const AUDIT_EVENT_SUMD_ANKETAAPPROVE = 'SUMD_ANKETAAPPROVE';
export const AUDIT_EVENT_SUMD_EXPORTLISTANKET = 'SUMD_EXPORTLISTANKET';
export const AUDIT_EVENT_SUMD_EXPORTANKETA = 'SUMD_EXPORTANKETA';

export const DEFAULT_SIDECAR_URL = 'http://localhost:8081/api/v2/audit';
export const DEFAULT_TIMEOUT_MS = 3000;
export const DEFAULT_RETRY_INTERVAL_MS = 30000;