export const AUDIT_EVENT_SUMD_CREATEANKETA = 'SUMD_CREATEANKETA';
export const AUDIT_EVENT_SUMD_SAVEANKETA = 'SUMD_SAVEANKETA';
export const AUDIT_EVENT_SUMD_DELETEANKETA = 'SUMD_DELETEANKETA';
export const AUDIT_EVENT_SUMD_HOLDANKETA = 'SUMD_HOLDANKETA';
export const AUDIT_EVENT_SUMD_APPROVE = 'SUMD_APPROVE';
export const AUDIT_EVENT_SUMD_EXPORT = 'SUMD_EXPORT';

export const DEFAULT_SIDECAR_URL = 'http://localhost:8081/api/v2/audit';
export const DEFAULT_TIMEOUT_MS = 3000;
export const DEFAULT_RETRY_INTERVAL_MS = 30000;