import type { AppRouteConfig } from "./types";

export const navbarGroups = {
	adminV2: { title: "Администрирование" },
	tracker: { title: "Трекер" },
	dev: { title: "Разработка" },
} as const;

/** Общие маршруты: админка v2 (контент) и playground. Не привязаны к /v1 или /v2. */
export const commonRoutes = {
	settings: {
		rootPath: "/settings",
		name: "Настройки",
		disabled: false,
	},
	admin: {
		rootPath: "/admin",
		name: "Администрирование",
		disabled: false,
	},
	adminV2Schemas: {
		rootPath: "/admin/schemas",
		name: "Схемы",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "adminV2", order: 0 },
	},
	adminV2Guide: {
		rootPath: "/admin/guide",
		name: "Справка",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "adminV2", order: 3 },
	},
	adminV2Dictionaries: {
		rootPath: "/admin/dictionaries",
		name: "Справочники",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "adminV2", order: 5 },
	},
	adminV2TypicalWorks: {
		rootPath: "/admin/typical-works",
		name: "Типовые работы",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "adminV2", order: 6 },
	},
	adminV2Formulas: {
		rootPath: "/admin/formulas",
		name: "Формулы",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "adminV2", order: 7 },
	},
	adminV2Settings: {
		rootPath: "/admin/settings",
		name: "Настройки",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "adminV2", order: 8 },
	},
	adminV2TypicalWorkDetail: {
		rootPath: "/admin/typical-works/:workId",
		name: "Типовая работа",
		shortName: "Типовая работа",
		disabled: false,
	},
	adminV2DictionaryDetail: {
		rootPath: "/admin/dictionaries/:dictionaryId",
		name: "Справочник",
		shortName: "Справочник",
		disabled: false,
	},
	adminV2History: {
		rootPath: "/admin/history",
		name: "История сохранений",
		disabled: false,
		showInNavbar: false,
	},
	adminV2TemplateHistory: {
		rootPath: "/admin/schemas/:templateId/history",
		name: "История изменений шаблона",
		shortName: "История",
		disabled: false,
	},
	adminV2TemplateEditor: {
		rootPath: "/admin/templates/:templateId/edit",
		name: "Редактор JSON-схемы",
		shortName: "Редактор",
		disabled: false,
	},
	adminV2TemplateRead: {
		rootPath: "/admin/templates/:templateId/read",
		name: "Предпросмотр формы",
		shortName: "Просмотр",
		disabled: false,
	},
	adminV2TemplateLogic: {
		rootPath: "/admin/templates/:templateId/logic",
		name: "Редактор логики",
		shortName: "Логика",
		disabled: false,
	},
	tracker: {
		rootPath: "/tracker",
		name: "Трекер",
		disabled: false,
	},
	trackerProjects: {
		rootPath: "/tracker/projects",
		name: "Проекты",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "tracker", order: 0 },
	},
	trackerBoards: {
		rootPath: "/tracker/boards",
		name: "Доски",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "tracker", order: 1 },
	},
	trackerTasks: {
		rootPath: "/tracker/tasks",
		name: "Задачи",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "tracker", order: 2 },
	},
	trackerGantt: {
		rootPath: "/tracker/gantt",
		name: "Диаграмма Ганта",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "tracker", order: 3 },
	},
	trackerAssignees: {
		rootPath: "/tracker/assignees",
		name: "Исполнители",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "tracker", order: 4 },
	},
	trackerCustomers: {
		rootPath: "/tracker/customers",
		name: "Заказчики",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "tracker", order: 5 },
	},
	trackerSupersprints: {
		rootPath: "/tracker/supersprints",
		name: "Суперспринты",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "tracker", order: 6 },
	},
	trackerSprints: {
		rootPath: "/tracker/sprints",
		name: "Спринты",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "tracker", order: 7 },
	},
	trackerStreams: {
		rootPath: "/tracker/streams",
		name: "Стримы",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "tracker", order: 8 },
	},
	trackerSettings: {
		rootPath: "/tracker/settings",
		name: "Настройки",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "tracker", order: 9 },
	},
	trackerHistory: {
		rootPath: "/tracker/history",
		name: "История",
		disabled: false,
		showInNavbar: true,
		navbar: { group: "tracker", order: 10 },
	},
	trackerBoardHistory: {
		rootPath: "/tracker/board/:boardKey/history",
		name: "История доски",
		shortName: "История",
		disabled: false,
	},
	trackerTaskCreate: {
		rootPath: "/tracker/task/new",
		name: "Новая задача",
		shortName: "Новая задача",
		disabled: false,
	},
	trackerBoardView: {
		rootPath: "/tracker/board/:boardKey",
		name: "Kanban-доска",
		shortName: "Доска",
		disabled: false,
	},
	trackerBoardTask: {
		rootPath: "/tracker/task/:taskKey",
		name: "Задача",
		shortName: "Задача",
		disabled: false,
	},
	playground: {
		name: "Песочница",
		rootPath: "/playground",
		devOnly: true,
		disabled: false,
		showInNavbar: true,
		navbar: { group: "dev", order: 0 },
	},
	kanbanBoard: {
		rootPath: "/playground/kanban-board",
		name: "Kanban-доска (legacy)",
		devOnly: true,
		disabled: true,
	},
	playgroundV2: {
		rootPath: "/playground/v2",
		name: "V2",
		devOnly: true,
		disabled: false,
	},
	playgroundV2TemplateEditor: {
		rootPath: "/playground/v2/templates/:templateId/edit",
		name: "V2 конструктор (песочница)",
		shortName: "Конструктор",
		devOnly: true,
		disabled: false,
	},
	playgroundV2TemplateRead: {
		rootPath: "/playground/v2/templates/:templateId/read",
		name: "Предпросмотр формы (песочница)",
		shortName: "Просмотр",
		devOnly: true,
		disabled: false,
	},
	playgroundV2TemplateLogic: {
		rootPath: "/playground/v2/templates/:templateId/logic",
		name: "Редактор логики (песочница)",
		shortName: "Логика",
		devOnly: true,
		disabled: false,
	},
} satisfies Record<string, AppRouteConfig>;
