/** data-test-id для режима редактирования шаблона (/edit). Ключ = значение, без суффиксов. */
export const V2_TEMPLATE_EDIT_TEST_IDS = {
	page: "page",
	header: "header",
	headerMeta: "headerMeta",
	headerActions: "headerActions",
	btnPreview: "btnPreview",
	btnLogic: "btnLogic",
	btnSave: "btnSave",
	btnActivate: "btnActivate",
	schemaEditor: "schemaEditor",
	dockLayout: "dockLayout",
	panelPalette: "panelPalette",
	panelProperties: "panelProperties",
	panelDesigner: "panelDesigner",
	panelJson: "panelJson",
	panelLogic: "panelLogic",
	panelPreview: "panelPreview",
	panelSchemaTree: "panelSchemaTree",
	panelRelations: "panelRelations",
	panelCalculation: "panelCalculation",
	cyclesWarning: "cyclesWarning",
	palette: "palette",
	paletteItem: "paletteItem",
	canvas: "canvas",
	canvasUndo: "canvasUndo",
	canvasRedo: "canvasRedo",
	canvasExpandAll: "canvasExpandAll",
	canvasCollapseAll: "canvasCollapseAll",
	canvasDropZone: "canvasDropZone",
	canvasFieldRow: "canvasFieldRow",
	canvasDuplicateField: "canvasDuplicateField",
	fieldTree: "fieldTree",
	properties: "properties",
	jsonEditor: "jsonEditor",
	jsonEditors: "jsonEditors",
	logicEditor: "logicEditor",
	previewEmbed: "previewEmbed",
	noDraft: "noDraft",
	panelChromeHeader: "panelChromeHeader",
} as const;

/** data-test-id для отдельной страницы логики (/logic). */
export const V2_TEMPLATE_LOGIC_TEST_IDS = {
	page: "logicPage",
	header: "logicHeader",
	headerMeta: "logicHeaderMeta",
	headerActions: "logicHeaderActions",
	btnEditor: "logicBtnEditor",
	btnSave: "logicBtnSave",
	btnActivate: "logicBtnActivate",
	logicWorkspace: "logicWorkspace",
} as const;

/** data-test-id для режима просмотра формы (/read). Ключ = значение, без суффиксов. */
export const V2_TEMPLATE_READ_TEST_IDS = {
	page: "page",
	header: "header",
	formPreview: "formPreview",
	form: "form",
	formSections: "formSections",
	formSection: "formSection",
	loading: "loading",
	noDraft: "noDraft",
} as const;
