export const list_mock = [
	{
		id: "278f5119-f900-49f2-b1bb-74f81e088852",
		name: "Тест Иван 1407-12",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "666",
		calculationResult: [
			{
				stageName: "Итоговая оценка",
				score: 140,
				stageBaseValue: 452,
				offset: -69.02654867256636,
			},
			{
				stageName: "01. Постановка задачи",
				score: 33,
				disabled: false,
				stageBaseValue: 33,
				percentFromAverage: 100,
				offset: 0,
			},
			{
				stageName: "02. Поиск данных",
				score: 0,
				disabled: true,
				stageBaseValue: 15,
				percentFromAverage: 0,
				offset: -100,
			},
			{
				stageName: "04. Построение витрины для разработки",
				score: 51,
				disabled: false,
				stageBaseValue: 51,
				percentFromAverage: 100,
				offset: 0,
			},
			{
				stageName: "05A. Разработка MVP",
				score: 0,
				disabled: true,
				stageBaseValue: 40,
				percentFromAverage: 0,
				offset: -100,
			},
			{
				stageName: "05. Разработка модели",
				score: 0,
				disabled: true,
				stageBaseValue: 37,
				percentFromAverage: 0,
				offset: -100,
			},
			{
				stageName: "AML разработка",
				score: 0,
				disabled: true,
				stageBaseValue: 68,
				percentFromAverage: 0,
				offset: -100,
			},
			{
				stageName: "05B. Пилотирование модели",
				score: 0,
				disabled: true,
				stageBaseValue: 34,
				percentFromAverage: 0,
				offset: -100,
			},
			{
				stageName: "06. Разработка витрины для применения модели",
				score: 56,
				disabled: false,
				stageBaseValue: 56,
				percentFromAverage: 100,
				offset: 0,
			},
			{
				stageName: "07. Адаптация и внедрение",
				score: 0,
				disabled: true,
				stageBaseValue: 50,
				percentFromAverage: 0,
				offset: -100,
			},
			{
				stageName: "AML внедрение",
				score: 0,
				disabled: true,
				stageBaseValue: 68,
				percentFromAverage: 0,
				offset: -100,
			},
		],
		questionnaireData: {
			name: "Тест Иван 1407-12",
			setupComplexity:
				"4 Сложность: Банком не планируется предоставление Модели регулятору для одобрения к использованию,но проведение регулярной валидации Моделей установлена Регулятором",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [
				{
					type: "planningRequirementGaps",
					probability: "Реализация не чаще 1 раза в 10 лет",
					influence:
						"Незначительное влияние на вторичные функции в рамках проектной деятельности",
				},
			],
			productionDeploymentChannels: ["Стриминг"],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "1",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_Классические модели",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "",
		},
		finalCoefficient: 340.94,
		createdAt: "2025-07-14T16:19:17.805Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "c7d8b12a-97df-4981-937f-0c055b12ac1c",
		name: "Тест Иван 1407-11",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "Тест Иван 1407-11",
			setupComplexity:
				"1 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "1",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_Классические модели",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 201.25,
		createdAt: "2025-07-14T16:17:54.642Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "f30b33de-653c-47da-922c-6c1653ccbd8a",
		name: "Тест Иван 1407-10",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "Тест Иван 1407-10",
			setupComplexity:
				"1 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "1",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 206.8,
		createdAt: "2025-07-14T16:00:52.066Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "d0a5b83b-0923-4b7e-a5e8-d743647f6b1a",
		name: "Тест Иван 1407-9",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: [
			"Департамент операционной поддержки бизнеса",
			"Департамент анализа данных и моделирования",
			"Департамент по работе с массовым сегментом",
		],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "Тест Иван 1407-9",
			setupComplexity:
				"4 Сложность: Банком не планируется предоставление Модели регулятору для одобрения к использованию,но проведение регулярной валидации Моделей установлена Регулятором",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Табличные данные",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 293.57,
		createdAt: "2025-07-14T15:55:50.142Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "c5a52798-7ec9-45e7-aa89-e775974044d6",
		name: "Тест Иван 1407-8",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: [
			"Депозитарий",
			"Департамент операционной поддержки бизнеса",
			"Департамент по работе с персоналом",
			"Департамент корпоративных кредитных рисков",
			"Департамент по работе со СМИ",
			"Департамент по работе с массовым сегментом",
		],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "Тест Иван 1407-8",
			setupComplexity:
				"1 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 191.8,
		createdAt: "2025-07-14T15:54:57.337Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "1caaebd4-3401-400c-af16-5a0552ac0591",
		name: "Тест Иван 1407-7",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент анализа данных и моделирования"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "Тест Иван 1407-7",
			setupComplexity:
				"1 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Табличные данные",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 167.75,
		createdAt: "2025-07-14T15:37:29.985Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "1b301922-8a29-4e03-ba4b-9aa58182d3d1",
		name: "test_ivan_1407_6",
		rfd: "Отсутствует",
		streamExecutor: "Финансовое моделирование",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_ivan_1407_6",
			setupComplexity:
				"1 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 191.8,
		createdAt: "2025-07-14T15:36:45.231Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "d4c015bc-cb3d-4808-844d-ef5bade43b8c",
		name: "Тест Иван 1407-5",
		rfd: "Отсутствует",
		streamExecutor: "Финансовое моделирование",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "Тест Иван 1407-5",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Аудио Аналитика",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 249,
		createdAt: "2025-07-14T15:35:36.621Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "81e5320a-5ec9-45a0-820f-ffe241a476c1",
		name: "hello world 3",
		rfd: "Отсутствует",
		streamExecutor: "Финансовое моделирование",
		department: ["Департамент по работе со СМИ"],
		customerName: "ывапывап",
		comment: "ывапывап",
		questionnaireData: {
			name: "hello world 3",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "4-10 мес.",
			initiativeCost: "45.3-438 млн.",
			modelsCount: 1,
			uncertaintyAdjustment: 30,
			generalUncertainty: [],
			readyPromReports: "Нет",
			assessedInitiativesCount: "99",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 138.65,
		createdAt: "2025-07-14T14:42:34.795Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "d7d128f1-61d9-45ee-ad17-4e9533bc718e",
		name: "test_3555555666546",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_3555555666546",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Аудио Аналитика",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 127.63,
		createdAt: "2025-07-11T23:44:07.718Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "a87ffde1-93cb-481e-aa42-027142aba1ac",
		name: "test_3",
		rfd: "Отсутствует",
		streamExecutor: "Моделирование РБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "Сирожа Слезла Кожа",
		comment: "",
		questionnaireData: {
			name: "test_3",
			setupComplexity:
				"1 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Аудио Аналитика",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "44",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 1957.1,
		createdAt: "2025-07-11T22:59:27.506Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "a388eea2-67eb-4d36-9595-60c6750e80e0",
		name: "test_3",
		rfd: "Отсутствует",
		streamExecutor: "Моделирование РБ",
		department: ["Департамент по работе с персоналом"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_3",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 53.010000000000005,
		createdAt: "2025-07-11T19:52:56.595Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "2d69e116-07cf-4379-b0cc-bd1956a495f7",
		name: "Test Sohran",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Специальный отдел"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "Test Sohran",
			setupComplexity:
				"3 Сложность: Проведение регулярной валидации Моделей Регулятором нормативно не установлено. Заказчик запрашивает проведение первичной валидации модели",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_Классические модели",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 59.44,
		createdAt: "2025-07-11T18:36:19.906Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "986acefe-84cb-433d-ad03-c5c0e5920382",
		name: "test_355555",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_355555",
			setupComplexity:
				"3 Сложность: Проведение регулярной валидации Моделей Регулятором нормативно не установлено. Заказчик запрашивает проведение первичной валидации модели",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Аудио Аналитика",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 69.15,
		createdAt: "2025-07-11T18:21:37.489Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "1fcf103b-050a-4855-bed8-a7a2d45aba06",
		name: "test_3",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_3",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Компьютерное зрение_CV",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 62.260000000000005,
		createdAt: "2025-07-11T18:02:57.872Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "afa18ec2-f9d7-449f-8626-917cb1cd6f51",
		name: "test_3",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Депозитарий"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_3",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Аудио Аналитика",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 57.629999999999995,
		createdAt: "2025-07-11T17:58:16.357Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "4473e0c0-237d-4495-9308-0bbc3b96dae1",
		name: "test_3",
		rfd: "Отсутствует",
		streamExecutor: "Моделирование РБ",
		department: ["Департамент по работе с персоналом"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_3",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_Классические модели",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: ["LLM"],
		},
		finalCoefficient: 205.79,
		createdAt: "2025-07-11T17:45:09.471Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "e891b841-36f5-4c6d-8210-2c4597c2c642",
		name: "test_3",
		rfd: "Отсутствует",
		streamExecutor: "Моделирование РБ",
		department: ["Департамент по работе с персоналом"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_3",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_Классические модели",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: ["LLM"],
		},
		finalCoefficient: 205.79,
		createdAt: "2025-07-11T17:45:09.465Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "6f99339a-53fc-4320-9ac5-bb6dcbd27efc",
		name: "test_3",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент по работе со СМИ"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_3",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "10-18 мес.",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Аудио Аналитика",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: ["Мобильные устройства"],
		},
		finalCoefficient: 272.63,
		createdAt: "2025-07-11T17:32:36.419Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "0ec51bdd-5d80-4d4a-a105-637594311411",
		name: "test_2",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_2",
			setupComplexity:
				"3 Сложность: Проведение регулярной валидации Моделей Регулятором нормативно не установлено. Заказчик запрашивает проведение первичной валидации модели",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_Классические модели",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: ["Стриминг"],
		},
		finalCoefficient: 200.07,
		createdAt: "2025-07-11T17:31:38.424Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "7da6d063-f5f0-4722-b6d0-14f0deeef18b",
		name: "test_3",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент корпоративных кредитных рисков"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_3",
			setupComplexity:
				"3 Сложность: Проведение регулярной валидации Моделей Регулятором нормативно не установлено. Заказчик запрашивает проведение первичной валидации модели",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Аудио Аналитика",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: ["LLM"],
		},
		finalCoefficient: 309.15,
		createdAt: "2025-07-11T17:30:49.535Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "5ee28c42-7e9a-42a6-baf2-3c64504d69e2",
		name: "test_2",
		rfd: "Отсутствует",
		streamExecutor: "Моделирование РБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_2",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: ["Стриминг"],
		},
		finalCoefficient: 184.26,
		createdAt: "2025-07-11T17:30:16.066Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "562f4d30-eb60-435a-8006-988ec18caef2",
		name: "test_3",
		rfd: "Отсутствует",
		streamExecutor: "Моделирование РБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_3",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "",
			initiativeCost: "",
			modelsCount: 1,
			uncertaintyAdjustment: 0,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Аудио Аналитика",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: ["LLM"],
		},
		finalCoefficient: 257.63,
		createdAt: "2025-07-11T17:28:00.886Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "97cc64fd-cc19-46c4-a399-1358ffe4f8c5",
		name: "сява",
		rfd: "RFD-1241241",
		streamExecutor: "Финансовое моделирование",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "сява",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			modelsCount: 1,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Компьютерное зрение_CV",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 107.25999999999999,
		createdAt: "2025-07-11T16:17:20.505Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "b33f0315-d3db-4cec-a33e-03916df39e90",
		name: "asdf",
		rfd: "RFD-124124",
		streamExecutor: "Моделирование РБ",
		department: ["Департамент по работе с персоналом"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "asdf",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			modelsCount: 1,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 53.010000000000005,
		createdAt: "2025-07-11T16:09:04.012Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "5058f672-809c-46d3-987b-c91dd761a162",
		name: "Оценка проекта для бизнеса",
		rfd: "Отсутствует",
		streamExecutor: "Стрим 2",
		department: ["Департамент аналитики"],
		customerName: "Иванов Иван Иванович",
		comment: "Дополнительные комментарии",
		questionnaireData: {
			name: "Оценка проекта для бизнеса",
			setupComplexity:
				"1 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено",
			initiativeTimeline: "Менее 1 мес.",
			initiativeCost: "45.3-438 млн.",
			modelsCount: 2,
			uncertaintyAdjustment: 3,
			generalUncertainty: [
				{
					type: "planningRequirementGaps",
					probability: "Реализация не чаще 1 раза в 10 лет",
					influence:
						"Незначительное влияние на вторичные функции в рамках проектной деятельности",
				},
			],
			readyPromReports: "Нет",
			assessedInitiativesCount: "3",
			dataSourcesCount: "4",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Да",
			productionAdditionalReports: "4",
			productionDeploymentChannels: [
				"Батч",
				"Батч+загрузка данных потребителю",
				"Батч + Онлайн",
			],
		},
		finalCoefficient: 1.8,
		createdAt: "2025-07-11T15:57:30.293Z",
		author: "Система",
	},
	{
		id: "f5f14968-070d-4ddc-8cb5-33ab3582cd91",
		name: "12344",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Депозитарий"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "12344",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			modelsCount: 1,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Табличные данные",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 37.97,
		createdAt: "2025-07-11T12:09:31.353Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "9851da00-01b5-4b41-9679-c5b83c30725d",
		name: "sdf",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "sdf",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			modelsCount: 1,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Аудио Аналитика",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: ["Внедрение в облаке"],
		},
		finalCoefficient: 364.63,
		createdAt: "2025-07-11T11:44:46.060Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "17e0bb0a-da98-478c-bf49-093561d9afce",
		name: "Тест 11.07",
		rfd: "RFD-2332",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "Тест 11.07",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "Менее 1 мес.",
			initiativeCost: "438-870 млн.",
			modelsCount: 1,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Табличные данные",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 37.97,
		createdAt: "2025-07-11T11:07:18.611Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "5960ecfc-744e-4a9d-92df-dab03a5f54f2",
		name: "test_jul10_21_41",
		rfd: "RFD-45345435345",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент по работе с персоналом"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_jul10_21_41",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			modelsCount: 1,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "0",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 105.00999999999999,
		createdAt: "2025-07-10T21:42:21.817Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "c7a2e969-5cda-433a-aa73-ee9a3a880976",
		name: "test_jul10_20_02",
		rfd: "RFD-45345435345",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент по работе с персоналом"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_jul10_20_02",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "1-4 мес.",
			initiativeCost: "870 млн. - 2 млрд.",
			modelsCount: 1,
			generalUncertainty: [
				{
					type: "qualifiedStaffShortage",
					probability: "Реализация 1 раз в 1-3 года",
					influence:
						"Значительный негативный эффект на возможность достижения целей проекта",
				},
			],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "4",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 99,
		createdAt: "2025-07-10T20:04:04.287Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "53f499a0-c66a-411b-928b-adf0d1d1b24c",
		name: "test_jul10_20_02",
		rfd: "RFD-45345435345",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент по работе с персоналом"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_jul10_20_02",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "1-4 мес.",
			initiativeCost: "870 млн. - 2 млрд.",
			modelsCount: 1,
			generalUncertainty: [
				{
					type: "qualifiedStaffShortage",
					probability: "Реализация 1 раз в 1-3 года",
					influence:
						"Значительный негативный эффект на возможность достижения целей проекта",
				},
			],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "4",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 99,
		createdAt: "2025-07-10T20:03:53.214Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "b950c896-fac1-4d8a-8dbd-beb95b3d49f5",
		name: "test_jul10_20_02",
		rfd: "RFD-45345435345",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент по работе с персоналом"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_jul10_20_02",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "1-4 мес.",
			initiativeCost: "870 млн. - 2 млрд.",
			modelsCount: 1,
			generalUncertainty: [
				{
					type: "qualifiedStaffShortage",
					probability: "Реализация 1 раз в 1-3 года",
					influence:
						"Значительный негативный эффект на возможность достижения целей проекта",
				},
			],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "4",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "Не требуется",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 318.59,
		createdAt: "2025-07-10T20:03:24.368Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "b86243b0-9114-4e39-9950-8481f603598e",
		name: "333",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент корпоративных кредитных рисков"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "333",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "1-4 мес.",
			initiativeCost: "870 млн. - 2 млрд.",
			modelsCount: 1,
			generalUncertainty: [
				{
					type: "contractorPerformanceIssues",
					probability: "Реализация 1 раз в год",
					influence:
						"Незначительное влияние на задачи и сроки достижения целей проекта",
				},
			],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "2",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Да",
			productionAdditionalReports: "7",
			productionDeploymentChannels: ["Гео-сервисы"],
		},
		finalCoefficient: 1148,
		createdAt: "2025-07-10T13:30:57.798Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "e2f8e7e5-e9dd-4560-8e9d-4953e5229b51",
		name: "test_4",
		rfd: "RFD-44543534",
		streamExecutor: "Моделирование РБ",
		department: ["Департамент по работе с персоналом"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_4",
			setupComplexity:
				"3 Сложность: Проведение регулярной валидации Моделей Регулятором нормативно не установлено. Заказчик запрашивает проведение первичной валидации модели",
			initiativeTimeline: "4-10 мес.",
			initiativeCost: "45.3-438 млн.",
			modelsCount: 1,
			uncertaintyAdjustment: 3,
			generalUncertainty: [
				{
					type: "planningRequirementGaps",
					probability: "Реализация 1 раз в 1-3 года",
					influence:
						"Реализация проекта с контролируемыми отклонениями от изначальных целей",
				},
			],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "5",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Аудио Аналитика",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Да",
			productionAdditionalReports: "9",
			productionDeploymentChannels: ["Гео-сервисы"],
		},
		finalCoefficient: 1436.96,
		createdAt: "2025-07-09T20:20:38.123Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "1d3a214c-6713-489a-83dc-696efec13490",
		name: "asdf",
		rfd: "Отсутствует",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "asdf",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "1-4 мес.",
			initiativeCost: "438-870 млн.",
			modelsCount: 1,
			uncertaintyAdjustment: 2,
			generalUncertainty: [],
			readyPromReports: "Нет",
			assessedInitiativesCount: "1",
			dataSourcesCount: "5",
			pilotModelRequired: "Не требуется",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "6",
			productionDeploymentChannels: ["LLM"],
		},
		finalCoefficient: 718.3599999999999,
		createdAt: "2025-07-09T15:38:39.181Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "039a9fde-28ab-4558-8ce1-a3f44ba06407",
		name: "test_3",
		rfd: "RFD-33333333",
		streamExecutor: "Моделирование RnD",
		department: [
			"Департамент корпоративных кредитных рисков",
			"Департамент инвестиционных продуктов",
		],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_3",
			setupComplexity:
				"4 Сложность: Банком не планируется предоставление Модели регулятору для одобрения к использованию,но проведение регулярной валидации Моделей установлена Регулятором",
			initiativeTimeline: "4-10 мес.",
			initiativeCost: "До 45.3 млн.",
			modelsCount: 1,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "3",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "7",
			productionDeploymentChannels: [],
		},
		finalCoefficient: 679.21,
		createdAt: "2025-07-09T14:29:36.040Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "37323c3b-ab3b-44b1-87fc-6106bdde2d1a",
		name: "test_2",
		rfd: "RFD-222222",
		streamExecutor: "Разработка моделей для КМБ и КСБ",
		department: [
			"Департамент по работе с персоналом",
			"Департамент по работе со СМИ",
		],
		customerName: "",
		comment: "",
		questionnaireData: {
			name: "test_2",
			setupComplexity:
				"4 Сложность: Банком не планируется предоставление Модели регулятору для одобрения к использованию,но проведение регулярной валидации Моделей установлена Регулятором",
			initiativeTimeline: "4-10 мес.",
			initiativeCost: "438-870 млн.",
			modelsCount: 1,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "2",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Компьютерное зрение_CV",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "7",
			productionDeploymentChannels: ["Стриминг"],
		},
		finalCoefficient: 942.41,
		createdAt: "2025-07-09T14:12:16.643Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "27355575-2181-4662-831c-a564d7b81c82",
		name: "test_666",
		rfd: "RFD-66666",
		streamExecutor: "Моделирование РБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "",
		comment: "3333",
		questionnaireData: {
			name: "test_666",
			setupComplexity:
				"1 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено",
			initiativeTimeline: "4-10 мес.",
			initiativeCost: "438-870 млн.",
			modelsCount: 1,
			uncertaintyAdjustment: 3,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "1",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Аудио Аналитика",
				},
			],
			pilotSupportRequired: "Не требуется",
			autoMlRequired: "Не требуется",
			productionAdditionalReports: "7",
			productionDeploymentChannels: ["LLM"],
		},
		finalCoefficient: 562.49,
		createdAt: "2025-07-09T14:05:15.052Z",
		author: "test_ds_lead test_ds_lead",
	},
	{
		id: "c165a33f-2665-4c36-910c-15d8bbf15c0d",
		name: "asdf",
		rfd: "RFD-12414",
		streamExecutor: "Моделирование РБ",
		department: ["Департамент операционной поддержки бизнеса"],
		customerName: "asdf",
		comment: "asdf",
		questionnaireData: {
			name: "asdf",
			setupComplexity:
				"2 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено. Модель оценки риска",
			initiativeTimeline: "4-10 мес.",
			initiativeCost: "45.3-438 млн.",
			modelsCount: 1,
			uncertaintyAdjustment: 30,
			generalUncertainty: [],
			readyPromReports: "Да",
			assessedInitiativesCount: "1",
			dataSourcesCount: "4",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Да",
			productionAdditionalReports: "6",
			productionDeploymentChannels: ["Гео-сервисы"],
		},
		finalCoefficient: 1045.7,
		createdAt: "2025-07-09T12:39:15.959Z",
		author: "test_ds test_ds",
	},
	{
		id: "52a5238e-308c-4646-be3b-133596b8e0c6",
		name: "Оценка проекта для бизнеса",
		rfd: "Отсутствует",
		streamExecutor: "Стрим 2",
		department: ["Департамент аналитики"],
		customerName: "Иванов Иван Иванович",
		comment: "Дополнительные комментарии",
		questionnaireData: {
			name: "Оценка проекта для бизнеса",
			setupComplexity:
				"1 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено",
			initiativeTimeline: "Менее 1 мес.",
			initiativeCost: "45.3-438 млн.",
			modelsCount: 2,
			uncertaintyAdjustment: 3,
			generalUncertainty: [
				{
					type: "planningRequirementGaps",
					probability: "Реализация не чаще 1 раза в 10 лет",
					influence: "Незначительное",
				},
			],
			readyPromReports: "Нет",
			assessedInitiativesCount: "3",
			dataSourcesCount: "4",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Да",
			productionAdditionalReports: "4",
			productionDeploymentChannels: [
				"Батч",
				"Батч+загрузка данных потребителю",
				"Батч + Онлайн",
			],
		},
		finalCoefficient: 1.8,
		createdAt: "2025-07-09T12:35:32.744Z",
		author: "test_ds test_ds",
	},
	{
		id: "46e1f3b6-9921-4e93-a8ba-4d634c936991",
		name: "Оценка проекта для бизнеса",
		rfd: null,
		streamExecutor: null,
		department: null,
		customerName: null,
		comment: null,
		questionnaireData: {
			name: "Оценка проекта для бизнеса",
			setupComplexity:
				"1 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено",
			initiativeTimeline: "Менее 1 мес.",
			initiativeCost: "45.3-438 млн.",
			modelsCount: 2,
			uncertaintyAdjustment: 3,
			generalUncertainty: [
				{
					type: "planningRequirementGaps",
					probability: "Реализация не чаще 1 раза в 10 лет",
					influence: "Незначительное",
				},
			],
			readyPromReports: "Нет",
			assessedInitiativesCount: "3",
			dataSourcesCount: "4",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Да",
			productionAdditionalReports: "4",
			productionDeploymentChannels: [
				"Батч",
				"Батч+загрузка данных потребителю",
				"Батч + Онлайн",
			],
		},
		finalCoefficient: 1.8,
		createdAt: "2025-07-08T15:33:02.222Z",
		author: null,
	},
	{
		id: "9e9f2839-4fb2-4293-ab85-2cad1a04c67e",
		name: "Оценка проекта для бизнеса",
		rfd: null,
		streamExecutor: null,
		department: null,
		customerName: null,
		comment: null,
		questionnaireData: {
			name: "Оценка проекта для бизнеса",
			setupComplexity:
				"1 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено",
			initiativeTimeline: "Менее 1 мес.",
			initiativeCost: "45.3-438 млн.",
			modelsCount: 2,
			uncertaintyAdjustment: 3,
			generalUncertainty: [
				{
					type: "planningRequirementGaps",
					probability: "Реализация не чаще 1 раза в 10 лет",
					influence: "Незначительное",
				},
			],
			readyPromReports: "Нет",
			assessedInitiativesCount: "3",
			dataSourcesCount: "4",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Да",
			productionAdditionalReports: "4",
			productionDeploymentChannels: [
				"Батч",
				"Батч+загрузка данных потребителю",
				"Батч + Онлайн",
			],
		},
		finalCoefficient: 1.8,
		createdAt: "2025-07-07T17:06:45.918Z",
		author: null,
	},
	{
		id: "94f1dd2f-f3c8-4d62-ab64-f41c78f46b9b",
		name: "Оценка проекта для бизнеса",
		rfd: null,
		streamExecutor: null,
		department: null,
		customerName: null,
		comment: null,
		questionnaireData: {
			name: "Оценка проекта для бизнеса",
			setupComplexity:
				"1 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено",
			initiativeTimeline: "Менее 1 мес.",
			initiativeCost: "45.3-438 млн.",
			modelsCount: 2,
			uncertaintyAdjustment: 3,
			generalUncertainty: [
				{
					type: "planningRequirementGaps",
					probability: "Реализация не чаще 1 раза в 10 лет",
					influence: "Незначительное",
				},
			],
			readyPromReports: "Нет",
			assessedInitiativesCount: "3",
			dataSourcesCount: "4",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Да",
			productionAdditionalReports: "4",
			productionDeploymentChannels: [
				"Батч",
				"Батч+загрузка данных потребителю",
				"Батч + Онлайн",
			],
		},
		finalCoefficient: 1.8,
		createdAt: "2025-07-07T15:46:35.842Z",
		author: null,
	},
	{
		id: "b6663d2f-befe-4e9a-922b-3989b15915c7",
		name: "Оценка проекта для бизнеса",
		rfd: null,
		streamExecutor: null,
		department: null,
		customerName: null,
		comment: null,
		questionnaireData: {
			name: "Оценка проекта для бизнеса",
			setupComplexity:
				"1 Сложность: Проведение регулярной валидации Моделей Регулятором не установлено",
			initiativeTimeline: "Менее 1 мес.",
			initiativeCost: "45.3-438 млн.",
			modelsCount: 2,
			uncertaintyAdjustment: 3,
			generalUncertainty: [
				{
					type: "planningRequirementGaps",
					probability: "Реализация не чаще 1 раза в 10 лет",
					influence: "Незначительное",
				},
			],
			readyPromReports: "Нет",
			assessedInitiativesCount: "3",
			dataSourcesCount: "4",
			pilotModelRequired: "Да",
			algorithmComplexity: [
				{
					algorithmType: "Текстовая аналитика_LLM",
				},
			],
			pilotSupportRequired: "Да",
			autoMlRequired: "Да",
			productionAdditionalReports: "4",
			productionDeploymentChannels: [
				"Батч",
				"Батч+загрузка данных потребителю",
				"Батч + Онлайн",
			],
		},
		finalCoefficient: 1.8,
		createdAt: "2025-07-03T16:31:11.915Z",
		author: null,
	},
];
